### ISSUE TITLE
Question: please explain the strategy of establishing connections in TalkActivity.java 

### ISSUE THREAD

**Issue by Bangybug** [sutiialex/Motolky#4]
Hi,

I'm wondering how group talk is being done in your application. I checked TalkActivity.java and found this:
```
    // Connect to the ones that have smaller lexicographical names than the local device name,
        // and listen for connections from the other ones.
        // For example say we have the following devices: bill, angie, jack and my
        // device name is bond. I will connect to angie and bill, but I will listen
        // for connections from jack.
```

Can you please explain why this is implemented that way?

**Comment by sutiialex** [comment]
Hi Dmitry,

If I remember correctly, in a Bluetooth IP connection there is always only
one server and one client. Now if you have two paired phones called Angie
and Jack, one of them has to decide to become the server and the other one
has to be the one that connects to the server. But they never before have
talked to each other to decide who is who. So how do they decide? You need
to be creative and come up with some strategy. Mine was based on names.
When two phones pair, they know already each other's name, without any
prior connection. So my decision was to sort the two names in alphabetical
order and make the greatest become the server and the smallest the client
that connects to that server. The nice part about this algorithm is that
both devices get to the same conclusion without having to talk to each
other.

In rest, there is nothing extra about a group communication. The idea is
that every phone has to connect to every other phone and for each of those
connections you have to decide who is the server and who is the client.

I hope this sheds some light. Let me know if you have further questions.

Cheers,
Alex

**Comment by Bangybug** [comment]
ok, got it, thanks!
